name: on Pull Request
run-name: ${{ github.actor }} on Pull Request
on: 
  pull_request: 
    types:
      - opened
    branches: [ "main","develope" ]
  workflow_dispatch:
jobs:
  # tests: //Оставил целенаправленно для для добавления тестов в будущем
  #   runs-on: ubuntu-latest
  #     steps:
  #     - name: get repository code
  #       uses: actions/checkout@v4
  #     - name: cache deps
  #       uses: actions/cache@v4
  #       with:
  #         path: ~/.npm
  #         key: node_modules-${{ hashFiles('**/package-lock.json')}}
  #     - name: install dependencies
  #       run: npm ci
  #     - name: test app
  #       run: npm run test
  eslint:
    runs-on: ubuntu-latest
    # needs: tests
    steps:
      - name: get repository code
        uses: actions/checkout@v4
  #Todo: когда добавим тесты. кешировать на их этапе
      - name: installing node
        uses: actions/setup-node@v4
        with: 
          node-version: 'latest'
      - name: cache deps
        uses: actions/cache@v4
        id: cache-modules
        with:
          path: ~/.npm
          key: node_modules-${{ hashFiles('**/package-lock.json')}}
      - if: ${{ steps.cache-modules.outputs.cache-hit != 'true' }}
        name: install dependencies
        continue-on-error: true
        run: npm ci
      - name: lint app
        run: npm run lint
  prettier:
    runs-on: ubuntu-latest
    # needs: tests
    needs: eslint
    steps:
      - name: get repository code
        uses: actions/checkout@v4
      - name: installing node
        uses: actions/setup-node@v4
        with: 
          node-version: 'latest'
      - name: cache deps
        uses: actions/cache@v4
        id: cache-modules
        with:
          path: ~/.npm
          key: node_modules-${{ hashFiles('**/package-lock.json')}}
      - if: ${{ steps.cache-modules.outputs.cache-hit != 'true' }}
        name: install dependencies
        continue-on-error: true
        run: npm ci
      - name: code formatting
        run: npm run prettier
